spring:
  profiles:
    active: local # local ?? ?? ??, prod : ?? (?? ?? ??)

  jpa:
    hibernate:
      ddl-auto: update # ?? ??, ??? prod.yml??
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

  flyway:
    enabled: false # 개발 환경에서는 JPA ddl-auto 사용

# 파일 업로드 설정
app:
  file:
    upload-dir: uploads/ownership

# Actuator 설정 (개발 환경에서만 사용)
management:
  endpoints:
    web:
      exposure:
        include: mappings, health, info


supabase:
  project-url: https://uapxufwstdldvgudedxy.supabase.co
  api-key: ${SUPABASE_SERVICE_ROLE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhcHh1ZndzdGRsZHZndWRlZHh5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODYwODcwNSwiZXhwIjoyMDc0MTg0NzA1fQ.EIYGNi_aleGvx3kB5VGJ8ufJR3TEWDKL-7vgCIClE84}
  storage:
    bucket: property_image
    base-folder: property